# Generated by Django 2.0 on 2018-02-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=20)),
                ('body', models.TextField(default='')),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
