# Generated by Django 2.0 on 2018-04-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sysconfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sysname', models.CharField(max_length=30)),
                ('testaddress', models.CharField(default='http://localhost/', max_length=100)),
                ('remark', models.TextField()),
            ],
        ),
    ]
