# Generated by Django 2.0 on 2018-04-14 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interfacetest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sysconfig',
            old_name='testaddress',
            new_name='host',
        ),
    ]
